### ISSUE TITLE
Avoid TOCTOU race on ports

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/falcon#35]
There is a TOCTUOU race here.

https://github.com/oxidecomputer/falcon/blob/cfc056ce9c9f93f9e531968f1f27d672699bc383/lib/src/lib.rs#L475-L478

See https://github.com/oxidecomputer/omicron/pull/2694#discussion_r1161894789

Ideally, we can find a stable illumos interface to get this information. Getting the information from `/proc/<pid>/fdinfo/<n>` would be nice, but I'm not sure if that is considered a stable interface.

**Comment by davepacheco** [comment]
Dup of #82 -- keeping that one open because it has more detail.
